name: Deploy on Events

on:
  repository_dispatch:
    types: [add-branch]

jobs:
  do_smth:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'cool cool'
      - run: echo ${{ github.event.client_payload.branch }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BINGO_TOKEN }}
      - run: |
          if grep -q "${{ github.event.client_payload.branch }}," bingo.csv; then
            echo "branch does exist";
          else 
            echo "${{ github.event.client_payload.branch }},y,y,y" >> bingo.csv
            git config --global user.name "some-bot"
            git config --global user.email "some-bot@users.noreply.github.com"
            git add bingo.csv
            git commit -m "adding ${{ github.event.client_payload.branch }} on behalf of tbd"
            git push
          fi
