name: Deploy on Events

on:
  repository_dispatch:
    types: [my-event]

jobs:
  do_smth:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'cool cool'
      - run: echo ${{ github.event.client_payload.branch }}