name: Remove Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to delete'
        required: true
        type: string

jobs:
  remove_branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.branch }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BINGO_TOKEN }}
      - run: |
          sed -i '/"${{ github.event.client_payload.branch }}",/d' bingo.csv
          git config --global user.name "some-bot"
          git config --global user.email "some-bot@users.noreply.github.com"
          git add bingo.csv
          git commit -m "removed ${{ github.event.client_payload.branch }} on behalf of tbd"
          git push